version: '3'

services: 
  xrayr: 
    image: ghcr.io/xrayr-project/xrayr:latest
    container_name: xrayr
    volumes:
      - ./config:/etc/XrayR/ # 映射配置文件夹
    restart: always
    depends_on:
      - nginx
    network_mode: host
    #network: trojan

  nginx:
      image: sjus4fun/nginx:0.5
      container_name: nginxt
      restart: always
      #ports:
      #    - 80:80
      #    - 4433:443
      volumes:
          - ./cert:/etc/nginx/cert
      environment:
          - TZ=Asia/Shanghai
      stdin_open: true
      tty: true
      network_mode: host
      #network: trojan
