version: '3' 
services:
    nginx:
        container_name: nginxv
        restart: always
        image: mynginxv 
        ports:
            - 81:80
        depends_on:
            - php
        volumes:
            - .:/usr/www/html
        environment:
            - TZ=Asia/Shanghai
    php:
        image: sjus4fun/vmq-php5.6:0.1
        container_name: vmq 
        restart: always
        #ports:
        #    - 80:80
        #    - 443:443
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        environment:
            - TZ=Asia/Shanghai
        depends_on:
            - mysql
        stdin_open: true
        tty: true
    mysql:
        image: mysql:5.6
        container_name: mysqlv
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=W1q2w3e.0
            - TZ=Asia/Shanghai
        volumes:
            - /var/lib/mysql:/var/lib/mysql
            - .:/db
        ports:
          - 3307:3306
    #phpmyadmin:
    #    image: phpmyadmin
    #    container_name: phpmyadminmetron
    #    restart: always
    #    ports:
    #      - 8080:80
    #    environment:
    #      - PMA_ARBITRARY=1

