version: '3' 
services:
    nginx:
        container_name: nginx
        restart: always
        image: nginx:1.22.1-alpine
        ports:
            - 82:80
        depends_on:
            - php
        volumes:
            - .:/usr/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        environment:
            - TZ=Asia/Shanghai
    php:
        image: sjus4fun/php7.2-fpm:0.3
        container_name: epay
        restart: always
        #ports:
        #    - 80:80
        #    - 443:443
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        environment:
            - TZ=Asia/Shanghai
        stdin_open: true
        tty: true
    #phpmyadmin:
    #    image: phpmyadmin
    #    container_name: phpmyadminmetron
    #    restart: always
    #    ports:
    #      - 8080:80
    #    environment:
    #      - PMA_ARBITRARY=1
