version: '3' 
services:
    nginx:
        container_name: nginx
        restart: always
        image: nginx:1.22.1-alpine
        #image:  gtary/ssp:nginx
        ports:
            - 80:80
            - 443:443
        depends_on:
            - php
        volumes:
            - .:/usr/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        environment:
            - TZ=Asia/Shanghai
    php:
        image: sjus4fun/php7.2-fpm:0.2
        container_name: sspanel
        restart: always
        #ports:
        #    - 80:80
        #    - 443:443
        volumes:
            - .:/var/www/html
        environment:
            - TZ=Asia/Shanghai
        depends_on:
            - mysql
        stdin_open: true
        tty: true
    mysql:
        image: mysql:5.6
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=W1q2w3e.0
            - TZ=Asia/Shanghai
        volumes:
            - /var/lib/mysql:/var/lib/mysql
            - ./sql:/tmp/sql
            - ./file/mariadb:/etc/mysql/conf.d
        ports:
          - 3306:3306
    #phpmyadmin:
    #    image: phpmyadmin
    #    container_name: phpmyadminmetron
    #    restart: always
    #    ports:
    #      - 8080:80
    #    environment:
    #      - PMA_ARBITRARY=1
